# Registered email: sadatmaliha703@gmail.com

In [ ]:
# You must run this code and use this dataset for all questions

import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

# Q1

In [ ]:
#array
print(emp_ages)
print(emp_income)

#data type
print(emp_ages.dtype)
print(emp_income.dtype)

#number of dimensions
print(emp_ages.ndim)
print(emp_income.ndim)

#shape
print(emp_ages.shape)
print(emp_income.shape)

#total number of elements
print(emp_ages.size)
print(emp_income.size)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
int64
int64
1
1
(50,)
(50,)
50
50

# Q2

In [ ]:
#maximum and minimum salary
print(np.max(emp_income))
print(np.min(emp_income))

#average salary
print(np.mean(emp_income))

#average age
print(np.mean(emp_ages))

94722
35452
68409.48
35.44

# Q3

In [ ]:
mask = ((emp_ages >= 25) & (emp_ages <= 40)) & (emp_income > 50000)

print(emp_ages[mask])
print(emp_income[mask])
print(np.sum(mask))

[37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]
[72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]
17

# Q4

In [ ]:
updated_array = np.array(emp_ages)

average_age = np.mean(emp_ages)

updated_array[updated_array < average_age] += 4
updated_array[updated_array >= average_age] += 2

print(emp_ages)
print(updated_array)
print(average_age)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
[56 27 24 45 39 39 25 41 28 40 35 41 33 40 31 47 53 50 24 38 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]
35.44

# Q5

In [ ]:
mask = (emp_roles == "Software Developer") | (emp_roles == "Backend Developer") | (emp_roles == "Digital Marketer")

increased_array = np.array(emp_income)
increased_array = increased_array.astype(np.float64)
increased_array[mask] *= 1.08

old_expense = np.sum(emp_income)
new_expense = np.sum(increased_array)
difference_of_expense = new_expense - old_expense

print(old_expense)
print(new_expense)
print(difference_of_expense)

3420474
3524808.08
104334.08000000007

#  Q6

In [ ]:
df = pd.read_csv("staff_data.csv")

display(df.head(3))

df.info()

display(df.describe())

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

# Q7

In [ ]:
filtered_df = df[['emp_id', 'emp_age', 'role']]
filtered_df = filtered_df[(filtered_df['emp_age'] >= 25) & (filtered_df['emp_age'] <= 40)]
filtered_df = filtered_df.sort_values(by=['emp_id'], ascending=[True])

filtered_df.iloc[-3:]

    emp_id  emp_age                 role
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

# Q8

In [ ]:
filtered_df = df[(df['role'] == "HR Manager") | (df['role'] == "HR Executive")]
display(filtered_df)

total_number_of_HR = ((df['role'] == "HR Manager") | (df['role'] == "HR Executive")).sum()
print(total_number_of_HR)

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager

9

# Q9

In [ ]:
sorted_df =  df.sort_values(by=['emp_age', 'emp_salary'], ascending=[True, False])
sorted_df = sorted_df[['emp_id', 'role', 'emp_salary']]

display(sorted_df.head())

    emp_id                role  emp_salary
30     131     Sales Executive       82550
18     119  Software Developer       63187
41     142    Digital Marketer       59500
2      103  Operations Manager       35452
36     137     Sales Executive       94427

# Q10

In [ ]:
df['previous_salary'] = df['emp_salary']
df['new_salary'] = df['emp_salary']

df.loc[(df['role'] == "Software Developer") | (df['role'] == "Backend Developer"), 'new_salary'] *= 1.12
df.loc[(df['role'] != "Software Developer") & (df['role'] != "Backend Developer"), 'new_salary'] *= 1.05

df['increase_of_salary'] = df['new_salary'] - df['previous_salary']

df = df[['role', 'previous_salary', 'new_salary', 'increase_of_salary']]

display(df)

/tmp/ipykernel_513/2007627293.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[80849.44 85298.08 76877.92 70769.44 83043.52 87756.48 57216.32 80941.28
 82111.68 97919.36 92210.72 81813.76]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['role'] == "Software Developer") | (df['role'] == "Backend Developer"), 'new_salary'] *= 1.12

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725    54311.25             2586.25
1            Accountant            38495    40419.75             1924.75
2    Operations Manager            35452    37224.60             1772.60
3      Digital Marketer            82295    86409.75             4114.75
4     Backend Developer            72187    80849.44             8662.44
5            HR Manager            58915    61860.75             2945.75
6     Backend Developer            76159    85298.08             9139.08
7       Sales Executive            92864    97507.20             4643.20
8       Sales Executive            76155    79962.75             3807.75
9          HR Executive            90494    95018.70             4524.70
10    Backend Developer            68641    76877.92             8236.92
11  Marketing Executive            48079    50482.95             2403.95
12      Sales Executive            56879    59722.95             2843.95
13   Operations Manager            83682    87866.10             4184.10
14     Digital Marketer            94722    99458.10             4736.10
15    Financial Analyst            91041    95593.05             4552.05
16      Sales Executive            48899    51343.95             2444.95
17   Operations Manager            68744    72181.20             3437.20
18   Software Developer            63187    70769.44             7582.44
19    Backend Developer            74146    83043.52             8897.52
20      Sales Executive            75641    79423.05             3782.05
21      Sales Executive            47678    50061.90             2383.90
22           Accountant            76760    80598.00             3838.00
23   Software Developer            78354    87756.48             9402.48
24         HR Executive            60584    63613.20             3029.20
25   Operations Manager            79898    83892.90             3994.90
26     Digital Marketer            59682    62666.10             2984.10
27         HR Executive            71888    75482.40             3594.40
28   Software Developer            51086    57216.32             6130.32
29           Accountant            73700    77385.00             3685.00
30      Sales Executive            82550    86677.50             4127.50
31  Marketing Executive            71447    75019.35             3572.35
32     Digital Marketer            76100    79905.00             3805.00
33    Backend Developer            72269    80941.28             8672.28
34   Software Developer            73314    82111.68             8797.68
35   Software Developer            87428    97919.36            10491.36
36      Sales Executive            94427    99148.35             4721.35
37           Accountant            84188    88397.40             4209.40
38           HR Manager            52013    54613.65             2600.65
39      Sales Executive            63326    66492.30             3166.30
40  Marketing Executive            44396    46615.80             2219.80
41     Digital Marketer            59500    62475.00             2975.00
42         HR Executive            55523    58299.15             2776.15
43           Accountant            58602    61532.10             2930.10
44         HR Executive            90794    95333.70             4539.70
45           HR Manager            41061    43114.05             2053.05
46   Software Developer            82331    92210.72             9879.72
47   Software Developer            73048    81813.76             8765.76
48     Digital Marketer            59727    62713.35             2986.35
49  Marketing Executive            50398    52917.90             2519.90